### ISSUE TITLE
Footer links to GitHub are incorrect

### ISSUE THREAD

**Issue by benlk** [OpenNewsLabs/field-guide-open-source-newsroom#122]
In the expandable Read The Docs footer on every page, the Github "view" and "edit" links are 404s:

- "View" goes to URLs like https://github.com/OpenNewsLabs/field-guide-open-source-newsroom/blob/master/home/docs/checkouts/readthedocs.org/user_builds/the-field-guide-to-open-source-in-the-newsroom/checkouts/latest/docs/contributing.md
- "Edit" goes to URLs like https://github.com/OpenNewsLabs/field-guide-open-source-newsroom/edit/master/home/docs/checkouts/readthedocs.org/user_builds/the-field-guide-to-open-source-in-the-newsroom/checkouts/latest/docs/contributing.md

That's the links here: 
<img width="319" alt="screen shot 2019-01-03 at 5 28 49 pm" src="https://user-images.githubusercontent.com/1754187/50665046-37065000-0f7d-11e9-9ab0-76058d5d5e67.png">

The links in page content on http://fieldguide.opennews.org/en/latest/contributing/ to various GitHub URLs are correct, so this appears to be a problem with the template rather than a problem with RTD.

**Comment by ryanpitts** [comment]
Thanks for spotting this! Looks like that's been an issue on and off for a while for RTD projects using Mkdocs for the build. The latest thread I found, where it looked like things had been fixed, [is here](https://github.com/rtfd/readthedocs.org/issues/1917). Added a report and will see if we can get this fixed soon.

**Comment by ryanpitts** [comment]
The bug was fixed, and getting it to render properly on our project just required a rebuild. Thanks for the alert!
