### ISSUE TITLE
Chapter 1 - add additional resources on licenses

### ISSUE THREAD

**Issue by tsl-lindsay** [OpenNewsLabs/field-guide-open-source-newsroom#2]
find this text:
> Let’s talk through the license options and figure out which one is best for our needs

todo:
Add more resources to this section. 

section: [https://github.com/OpenNewsLabs/field-guide-open-source-newsroom/blob/master/docs/Chapter01-Choosing-Open-Source.md#legalpr](https://github.com/OpenNewsLabs/field-guide-open-source-newsroom/blob/master/docs/Chapter01-Choosing-Open-Source.md#legalpr)

**Comment by ryanpitts** [comment]
closed in https://github.com/OpenNewsLabs/field-guide-open-source-newsroom/pull/54
